In [1]:
# import required libraries
import numpy as np
import pandas as pd

In [2]:
# Reading Dataset
df=pd.read_csv('drug200.csv')

In [3]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [4]:
df.shape

(200, 6)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [6]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [7]:
value_counts = df['Drug'].value_counts()
print(value_counts)

Drug
DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64


In [8]:
x=df.drop('Drug',axis=1)
y=df['Drug']

In [9]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 7.9+ KB


In [10]:
x.shape

(200, 5)

In [11]:
y

0      DrugY
1      drugC
2      drugC
3      drugX
4      DrugY
       ...  
195    drugC
196    drugC
197    drugX
198    drugX
199    drugX
Name: Drug, Length: 200, dtype: object

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [13]:
ct=ColumnTransformer([('oh',OneHotEncoder(),[1,2,3])],remainder='passthrough')

In [14]:
x=ct.fit_transform(x)

In [15]:
x.shape

(200, 9)

In [16]:
x

array([[ 1.   ,  0.   ,  1.   , ...,  0.   , 23.   , 25.355],
       [ 0.   ,  1.   ,  0.   , ...,  0.   , 47.   , 13.093],
       [ 0.   ,  1.   ,  0.   , ...,  0.   , 47.   , 10.114],
       ...,
       [ 0.   ,  1.   ,  0.   , ...,  0.   , 52.   ,  9.894],
       [ 0.   ,  1.   ,  0.   , ...,  1.   , 23.   , 14.02 ],
       [ 1.   ,  0.   ,  0.   , ...,  1.   , 40.   , 11.349]])

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()

In [19]:
y=le.fit_transform(y)

In [20]:
y

array([0, 3, 3, 4, 0, 4, 0, 3, 0, 0, 3, 0, 0, 0, 4, 0, 4, 1, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 4, 0, 0, 4, 2, 4, 0, 4, 4, 1, 4, 4, 4, 0, 2, 0, 4,
       4, 4, 1, 3, 0, 0, 0, 4, 0, 0, 2, 3, 2, 0, 4, 0, 0, 1, 0, 4, 2, 0,
       1, 4, 0, 0, 2, 0, 4, 0, 0, 0, 1, 0, 1, 4, 2, 4, 3, 1, 3, 2, 4, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1, 1, 3, 4, 0, 4, 4, 0, 2, 0,
       1, 4, 4, 4, 4, 0, 4, 4, 1, 0, 0, 0, 0, 0, 2, 0, 0, 4, 0, 4, 0, 0,
       4, 0, 0, 4, 2, 1, 2, 4, 1, 0, 2, 0, 1, 4, 4, 1, 4, 3, 1, 2, 4, 4,
       0, 3, 1, 0, 3, 4, 4, 2, 4, 0, 0, 0, 0, 4, 0, 1, 4, 4, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 4, 4, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 3, 0, 3, 3, 4,
       4, 4])

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=42)

In [22]:
x_train.shape, x_test.shape

((160, 9), (40, 9))

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [24]:
x_train

array([[ 1.03823026, -1.03823026, -0.79539491, ...,  1.1055416 ,
        -0.83405574, -0.74045911],
       [-0.96317747,  0.96317747, -0.79539491, ..., -0.90453403,
         0.41196591, -0.87126694],
       [ 1.03823026, -1.03823026, -0.79539491, ...,  1.1055416 ,
        -0.39794817, -0.89684776],
       ...,
       [ 1.03823026, -1.03823026,  1.25723711, ..., -0.90453403,
        -1.02095899,  1.83283243],
       [ 1.03823026, -1.03823026, -0.79539491, ..., -0.90453403,
         1.34648215, -0.04203377],
       [ 1.03823026, -1.03823026, -0.79539491, ..., -0.90453403,
        -1.08326007, -0.42422495]])

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [26]:
x.shape

(200, 9)

In [27]:
model=Sequential()#initiatiazation of model

In [35]:
model.add(Dense(units=9,activation='relu',kernel_initializer='random_uniform'))#Input layer

In [29]:
model.add(Dense(units=128,activation='relu',kernel_initializer='random_uniform'))#Hidden layer 1

In [30]:
model.add(Dense(units=64,activation='relu',kernel_initializer='random_uniform'))#Hidden layer 2

In [31]:
model.add(Dense(units=32,activation='relu',kernel_initializer='random_uniform'))#Hidden layer 3

In [32]:
model.add(Dense(units=1,activation='sigmoid',kernel_initializer='random_uniform'))#output layer

In [33]:
model.compile(optimizer='adam',loss='mse',metrics=['accuracy'])

In [34]:
model.fit(x_train,y_train,batch_size=32,epochs=90)

Epoch 1/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.1314 - loss: 4.0070
Epoch 2/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1005 - loss: 4.1795 
Epoch 3/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0910 - loss: 3.9168  
Epoch 4/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0910 - loss: 4.1600 
Epoch 5/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1235 - loss: 4.2070 
Epoch 6/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1018 - loss: 3.7368 
Epoch 7/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0984 - loss: 3.9604 
Epoch 8/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1292 - loss: 3.8514 
Epoch 9/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0853 - loss: 3.8287 
Epoch 10/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0979 - loss: 3.7378 
Epoch 11/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1296 - loss: 3.4040 
Epoch 12/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1240 - loss: 3.3568 
E